openapi: 3.0.1
info:
  title: Customer AS2 Connections
  description: Retrieve customer AS2 connections based on specified parameters.
  version: '1.0'
  x-ibm-application-name: Customer AS2 Connections
  x-ibm-application-id: customer-as2-connections
  x-ibm-annotations: 'true'
  x-ibm-skill-type: imported
servers:
  - url: https://certapi.onrender.com
security:
  - dummyAuth: []
paths:
  /internal/customer_as2_connections:
    get:
      summary: Retrieve customer AS2 connections
      description: Retrieve customer AS2 connections based on as2UrlDestination and/or as2IdTp parameters.
      parameters:
        - name: as2UrlDestination
          in: query
          required: false
          schema:
            type: string
          description: The AS2 URL destination to filter the connections.
        - name: as2IdTp
          in: query
          required: false
          schema:
            type: string
          description: The AS2 ID TP to filter the connections.
      responses:
        '200':
          description: Successful retrieval of the AS2 connection details.
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '400':
          description: Missing required parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: No connection details found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Connection details not found!
  securitySchemes:
    dummyAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
